name : Release

on:
  push:
    tags:
      - "v*"

jobs:
    publish: 
      name: Build and Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - uses: actions/setup-node@v2
          with:
            node-version: "16.x"

        - name: Checkout and pull branch
          run: |
            git branch
            git checkout main && git pull

        - name: Install Packages
          run: yarn install

        - name: Publish packages
          run: yarn lerna publish from-package --yes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        

    create-github-release:
      name: Create GitHub Release
      runs-on: ubuntu-latest
      needs: publish
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Create Release
          run: gh release create ${{ github.ref }} --generate-notes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}