name : Release

on:
  push:
    tags:
      - "v*"

jobs:
    publish: 
      name: Build and Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v2
          with:
            node-version: "16.x"
        - name: Git Identity
          run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          env:
            GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        - name: Checkout and pull branch
          run: git checkout main && git pull

        - name: Install Packages
          run: yarn install

        - name: Authenticate with Registry
          run: |
            yarn logout
            echo "@apollo-elements:registry=https://registry.npmjs.org/" > .npmrc
            echo "registry=https://registry.npmjs.org/" >> .npmrc
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
            npm whoami
          env:
            NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

        - name: Publish package 1
          working-directory: ./packages/package1
          run: pwd
          run: npm publish
          env:
            NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        - name: Publish package 2
          working-directory: ./packages/package2
          run: npm publish
          env:
            NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        

    create-github-release:
      name: Create GitHub Release
      runs-on: ubuntu-latest
      needs: publish
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Create Release
          run: gh release create ${{ github.ref }} --generate-notes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}