name : Release

on:
  push:
    tags:
      - "v*"

jobs:
    publish: 
      name: Build and Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '16.x'
            registry-url: 'https://registry.npmjs.org'
        - name: Authenticate with Registry
          run: echo "registry=//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
          env:
            NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        - name: Git Identity
          run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Install and Build 🔧
          run: | # Install npm packages and build the Storybook files
              yarn install
        - name: Publish #Publishes all packages to npm registry
          run: yarn lerna-publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        

    create-github-release:
      name: Create GitHub Release
      runs-on: ubuntu-latest
      needs: publish
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Create Release
          run: gh release create ${{ github.ref }} --generate-notes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}