name : Release

on:
  push:
    tags:
      - "v*"

jobs:
    publish: 
      name: Build and Publish
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-node@v2
          with:
            node-version: "16.x"

        - name: Install Packages
          run: yarn install

        - name: Authenticate with Registry
          run: |
            echo "registry=http://registry.npmjs.org/" >> .npmrc
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          env:
            NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

        - name: Publish packages
          run: yarn lerna publish from-package --yes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

        - name: Github Release
          run: gh release create ${{ github.ref }} --generate-notes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}